export const getArtworkByIdEnum = {
  IS_LOADING_ARTWORK_BY_ID: "IS_LOADING_ARTWORK_BY_ID",
  GET_ARTWORK_BY_ID_SUCCESS: "GET_ARTWORK_BY_ID_SUCCESS",
  GET_ARTWORK_BY_ID_ERROR: "GET_ARTWORK_BY_ID_ERROR",
};
