export const getArtworkHistoryEnum = {
  IS_LOADING_ARTWORK_HISTORY: "IS_LOADING_ARTWORK_HISTORY",
  GET_ARTWORK_HISTORY_SUCCESS: "GET_ARTWORK_HISTORY_SUCCESS",
  GET_ARTWORK_HISTORY_ERROR: "GET_ARTWORK_HISTORY_ERROR",
};
